Introduce `py::native_enum_kind` (mandatory argument without a default). (#30118)
* Fix `native_enum` `__module__` attribute: it needs to be a Python `str`.

* Exercise `enum_type.__module__`

* Consolidate `ENUM_TYPES_AND_MEMBERS`, `ENUM_TYPES` in test.

* Add test_pickle_roundtrip

* clang-tidy auto-fix

* Warning suppression for Clang 19 (unrelated to `native_enum` changes).

🐍 3 • Clang dev • C++11 • x64

```
-- The CXX compiler identification is Clang 19.0.0
```

```
/__w/pybind11k/pybind11k/include/pybind11/detail/function_record_pyobject.h:38:26: error: cast from 'PyObject *(*)(PyObject *, PyObject *, PyObject *)' (aka '_object *(*)(_object *, _object *, _object *)') to 'PyCFunction' (aka '_object *(*)(_object *, _object *)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
   38 |     = {{"__reduce_ex__", (PyCFunction) reduce_ex_impl, METH_VARARGS | METH_KEYWORDS, nullptr},
```

* Introduce `py::native_enum_kind` (mandatory argument without a default).

* Change `was_not_added_error_message()` based on feedback from @metzen